# crust:default_game_rules.toml
# This config allows the default game rules for world creation to be altered. Many game rules make testing easier, so
#   this is handy when you need to repeatedly generate new worlds.
# 
# For more information on game rules, see the in-game descriptions in the 'Create New World' menu or the Minecraft
#   Wiki article (https://minecraft.fandom.com/wiki/Game_rule).


# Whether this config file is enabled.
#  * Requires a GAME restart to take full effect *
# <Boolean> Valid Values: { true, false }, Default: false
config_enabled = false


# Category: player
# Default game rule settings for the 'player' category.

  player.artifacts.anglers_hat.luck_of_the_sea_level_bonus = 1
  player.artifacts.anglers_hat.lure_level_bonus = 1
  player.artifacts.antidote_vessel.enabled = true
  player.artifacts.antidote_vessel.max_effect_duration = 5
  player.artifacts.aqua_dashers.enabled = true
  player.artifacts.bunny_hoppers.do_cancel_fall_damage = true
  player.artifacts.bunny_hoppers.jump_boost_level = 2
  player.artifacts.charm_of_sinking.enabled = true
  player.artifacts.chorus_totem.cooldown = 0
  player.artifacts.chorus_totem.do_consume_on_use = true
  player.artifacts.chorus_totem.health_restored = 10
  player.artifacts.chorus_totem.teleportation_chance = 100
  player.artifacts.cloud_in_a_bottle.enabled = true
  player.artifacts.cloud_in_a_bottle.sprint_jump_horizontal_velocity = 50
  player.artifacts.cloud_in_a_bottle.sprint_jump_vertical_velocity = 50
  player.artifacts.cowboy_hat.speed_level = 2
  player.artifacts.cross_necklace.bonus_invincibility_ticks = 20
  player.artifacts.cross_necklace.cooldown = 0
  player.artifacts.crystal_heart.health_bonus = 10
  player.artifacts.digging_claws.dig_speed_bonus = 32
  player.artifacts.digging_claws.tool_tier = 2
  player.artifacts.eternal_steak.cooldown = 15
  player.artifacts.eternal_steak.enabled = true
  player.artifacts.everlasting_beef.cooldown = 15
  player.artifacts.everlasting_beef.enabled = true
  player.artifacts.feral_claws.attack_speed_bonus = 40
  player.artifacts.fire_gauntlet.fire_duration = 8
  player.artifacts.flame_pendant.cooldown = 0
  player.artifacts.flame_pendant.do_grant_fire_resistance = true
  player.artifacts.flame_pendant.fire_duration = 10
  player.artifacts.flame_pendant.strike_chance = 40
  player.artifacts.flippers.swim_speed_bonus = 100
  player.artifacts.golden_hook.experience_bonus = 75
  player.artifacts.helium_flamingo.flight_duration = 8
  player.artifacts.helium_flamingo.recharge_duration = 15
  player.artifacts.kitty_slippers.enabled = true
  player.artifacts.lucky_scarf.fortune_bonus = 1
  player.artifacts.night_vision_goggles.enabled = true
  player.artifacts.night_vision_goggles.strength = 25
  player.artifacts.novelty_drinking_hat.drinking_duration_multiplier = 30
  player.artifacts.novelty_drinking_hat.eating_duration_multiplier = 60
  player.artifacts.obsidian_skull.fire_resistance_cooldown = 60
  player.artifacts.obsidian_skull.fire_resistance_duration = 30
  player.artifacts.onion_ring.haste_duration_per_food_point = 6
  player.artifacts.onion_ring.haste_level = 2
  player.artifacts.panic_necklace.cooldown = 0
  player.artifacts.panic_necklace.speed_duration = 8
  player.artifacts.panic_necklace.speed_level = 1
  player.artifacts.pickaxe_heater.enabled = true
  player.artifacts.plastic_drinking_hat.drinking_duration_multiplier = 30
  player.artifacts.plastic_drinking_hat.eating_duration_multiplier = 60
  player.artifacts.pocket_piston.knockback_strength = 15
  player.artifacts.power_glove.attack_damage_bonus = 4
  player.artifacts.rooted_boots.do_grow_plants_after_eating = true
  player.artifacts.rooted_boots.enabled = true
  player.artifacts.rooted_boots.hunger_replenishing_duration = 15
  player.artifacts.running_shoes.do_increase_step_height = true
  player.artifacts.running_shoes.speed_bonus = 40
  player.artifacts.scarf_of_invisibility.enabled = true
  player.artifacts.shock_pendant.cooldown = 0
  player.artifacts.shock_pendant.do_cancel_lightning_damage = true
  player.artifacts.shock_pendant.strike_chance = 25
  player.artifacts.snorkel.enabled = true
  player.artifacts.snorkel.is_infinite = false
  player.artifacts.snorkel.water_breathing_duration = 15
  player.artifacts.snowshoes.allow_walking_on_powder_snow = true
  player.artifacts.snowshoes.slipperiness_reduction = 100
  player.artifacts.steadfast_spikes.enabled = true
  player.artifacts.steadfast_spikes.knockback_resistance = 10
  player.artifacts.superstitious_hat.looting_level_bonus = 1
  player.artifacts.thorn_pendant.cooldown = 0
  player.artifacts.thorn_pendant.max_damage = 6
  player.artifacts.thorn_pendant.min_damage = 2
  player.artifacts.thorn_pendant.strike_chance = 50
  player.artifacts.umbrella.is_glider = true
  player.artifacts.umbrella.is_shield = true
  player.artifacts.universal_attractor.enabled = true
  player.artifacts.vampiric_glove.absorption_chance = 100
  player.artifacts.vampiric_glove.absorption_ratio = 20
  player.artifacts.vampiric_glove.max_healing_per_hit = 6
  player.artifacts.villager_hat.reputation_bonus = 100
  player.artifacts.whoopee_cushion.fart_chance = 12
  player.disable_elytra_movement_check = false
  player.do_immediate_respawn = false
  player.do_limited_crafting = false
  player.drowning_damage = true
  player.fall_damage = true
  player.fire_damage = true
  player.freeze_damage = true
  player.keep_inventory = false
  player.natural_regeneration = true
  player.players_sleeping_percentage = 100
  player.spawn_radius = 10
  player.spectators_generate_chunks = true


# Category: mobs
# Default game rule settings for the 'mobs' category.

  mobs.disable_raids = false
  mobs.forgive_dead_players = true
  mobs.hunternibling = true
  mobs.max_entity_cramming = 24
  mobs.mob_griefing = true
  mobs.sunray = true
  mobs.universal_anger = false


# Category: spawning
# Default game rule settings for the 'spawning' category.

  spawning.do_insomnia = true
  spawning.do_mob_spawning = true
  spawning.do_patrol_spawning = true
  spawning.do_trader_spawning = true
  spawning.do_warden_spawning = true


# Category: drops
# Default game rule settings for the 'drops' category.

  drops.block_explosion_drop_decay = true
  drops.do_entity_drops = true
  drops.do_mob_loot = true
  drops.do_tile_drops = true
  drops.mob_explosion_drop_decay = true
  drops.tnt_explosion_drop_decay = false


# Category: updates
# Default game rule settings for the 'updates' category.

  updates.do_daylight_cycle = true
  updates.do_fire_tick = true
  updates.do_vines_spread = true
  updates.do_weather_cycle = true
  updates.fake_lava_source_conversion = false
  updates.fake_water_source_conversion = true
  updates.lava_source_conversion = false
  updates.random_tick_speed = 3
  updates.snow_accumulation_height = 1
  updates.water_source_conversion = true


# Category: chat
# Default game rule settings for the 'chat' category.

  chat.announce_advancements = true
  chat.command_block_output = true
  chat.log_admin_commands = true
  chat.send_command_feedback = true
  chat.show_death_messages = true


# Category: misc
# Default game rule settings for the 'misc' category.

  misc.command_modification_block_limit = 32768
  misc.global_sound_events = true
  misc.max_command_chain_length = 65536
  misc.reduced_debug_info = false
